name: Deploy Preview Branch

on:
  push:
    branches:
      - preview

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Deploy Hook
        env:
          DEPLOY_HOOK_URL: ${{ secrets.VERCEL_PREVIEW_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST $DEPLOY_HOOK_URL
